import type { Category, ContentType, FileRecord, PageRecord } from "./types";

export const TYPE_PAGE = 1;
export const TYPE_BLOG = 2;
export const TYPE_SLIDER = 3;

export const legacyContentTypes: ContentType[] = [
  {
    id: TYPE_PAGE,
    name: "Pages",
    title_label: "Title",
    summary_label: "Summary",
    text_label: "Content",
    has_picture: true,
    has_categories: false,
    has_tags: false,
    has_sub_images: true,
    has_sub_files: false,
    is_protected: false,
  },
  {
    id: TYPE_BLOG,
    name: "Blog",
    title_label: "Title",
    summary_label: "Summary",
    text_label: "Content",
    has_picture: true,
    has_categories: true,
    has_tags: true,
    has_sub_images: true,
    has_sub_files: false,
    is_protected: false,
  },
  {
    id: TYPE_SLIDER,
    name: "Slider",
    title_label: "Title",
    summary_label: "Description",
    text_label: "",
    has_picture: true,
    has_categories: false,
    has_tags: false,
    has_sub_images: false,
    has_sub_files: false,
    is_protected: false,
  },
];

export const legacyCategories: Category[] = [
  { id: 1, type_id: TYPE_BLOG, name: "Consciousness", rank: 1 },
  { id: 2, type_id: TYPE_BLOG, name: "Human", rank: 2 },
  { id: 3, type_id: TYPE_BLOG, name: "Book Notes", rank: 3 },
];

export const legacyPages: PageRecord[] = [
  {
    id: 1,
    sub_page_id: null,
    category_id: null,
    type_id: TYPE_PAGE,
    lang: "en",
    title: "About HCD",
    summary: "Human Consciousness Decoded introduces a structured way to question human awareness, perception and behavior.",
    body: "<p>HCD is a long-form project by Burak Akcakanat about human consciousness, awareness and the inner mechanics of perception. This rebuilt site keeps the original structure while moving the content system to Next.js and Supabase.</p>",
    picture_url: "books.jpg",
    rank: 1,
    chck1: false,
    chck2: false,
    val1: null,
    val2: null,
    val3: null,
    val4: null,
    val5: null,
    val6: null,
    val7: null,
    published: true,
    created_at: null,
    updated_at: null,
  },
  {
    id: 6,
    sub_page_id: null,
    category_id: null,
    type_id: TYPE_PAGE,
    lang: "en",
    title: "Contact",
    summary: "Contact Human Consciousness Decoded.",
    body: "<h3>Contact</h3><p>For questions, feedback and publishing inquiries, please use the quick contact form.</p><p><strong>Email:</strong> info@humanconsciousnessdecoded.com</p>",
    picture_url: null,
    rank: 2,
    chck1: false,
    chck2: false,
    val1: null,
    val2: null,
    val3: null,
    val4: null,
    val5: null,
    val6: null,
    val7: null,
    published: true,
    created_at: null,
    updated_at: null,
  },
  {
    id: 7,
    sub_page_id: null,
    category_id: null,
    type_id: TYPE_PAGE,
    lang: "en",
    title: "Human Consciousness Decoded",
    summary: "A book and research project focused on decoding the invisible habits that shape human experience.",
    body: "<p class=\"lead\">Human Consciousness Decoded is a practical and philosophical inquiry into consciousness, attention and identity.</p>",
    picture_url: "books2.jpg",
    rank: 3,
    chck1: false,
    chck2: false,
    val1: null,
    val2: null,
    val3: null,
    val4: null,
    val5: null,
    val6: null,
    val7: null,
    published: true,
    created_at: null,
    updated_at: null,
  },
  {
    id: 10,
    sub_page_id: null,
    category_id: 1,
    type_id: TYPE_BLOG,
    lang: "en",
    title: "What Is Consciousness?",
    summary: "A short introduction to the central question behind HCD.",
    body: "<p>Consciousness is often treated as a mystery, but it can also be examined through repeated patterns of perception, reaction and meaning.</p>",
    picture_url: "book-small.png",
    rank: 1,
    chck1: false,
    chck2: false,
    val1: null,
    val2: null,
    val3: null,
    val4: null,
    val5: null,
    val6: null,
    val7: null,
    published: true,
    created_at: null,
    updated_at: null,
  },
  {
    id: 11,
    sub_page_id: null,
    category_id: 2,
    type_id: TYPE_BLOG,
    lang: "en",
    title: "The Human Pattern",
    summary: "How repetition becomes personality and behavior.",
    body: "<p>Human behavior is shaped by stored responses. Seeing those responses clearly is the first practical step toward change.</p>",
    picture_url: "world.jpg",
    rank: 2,
    chck1: false,
    chck2: false,
    val1: null,
    val2: null,
    val3: null,
    val4: null,
    val5: null,
    val6: null,
    val7: null,
    published: true,
    created_at: null,
    updated_at: null,
  },
  {
    id: 12,
    sub_page_id: null,
    category_id: 3,
    type_id: TYPE_BLOG,
    lang: "en",
    title: "Reading HCD",
    summary: "Available formats and where to buy the book.",
    body: "<p>The first edition of Human Consciousness Decoded is available as e-book and paperback through external bookstores.</p>",
    picture_url: "books.jpg",
    rank: 3,
    chck1: false,
    chck2: false,
    val1: null,
    val2: null,
    val3: null,
    val4: null,
    val5: null,
    val6: null,
    val7: null,
    published: true,
    created_at: null,
    updated_at: null,
  },
  {
    id: 20,
    sub_page_id: null,
    category_id: null,
    type_id: TYPE_SLIDER,
    lang: "en",
    title: "Human Consciousness Decoded",
    summary: null,
    body: null,
    picture_url: "slide.png",
    rank: 1,
    chck1: false,
    chck2: false,
    val1: "Human Consciousness Decoded",
    val2: "A renewed home for Burak Akcakanat's book and consciousness project.",
    val3: "/i/1-about-hcd",
    val4: null,
    val5: null,
    val6: null,
    val7: null,
    published: true,
    created_at: null,
    updated_at: null,
  },
  {
    id: 21,
    sub_page_id: null,
    category_id: null,
    type_id: TYPE_SLIDER,
    lang: "en",
    title: "Read the Book",
    summary: null,
    body: null,
    picture_url: "books.jpg",
    rank: 2,
    chck1: false,
    chck2: false,
    val1: "Read the Book",
    val2: "Choose e-book or paperback editions through trusted external stores.",
    val3: "/books",
    val4: null,
    val5: null,
    val6: null,
    val7: null,
    published: true,
    created_at: null,
    updated_at: null,
  },
];

export const legacyFiles: FileRecord[] = [
  {
    id: 1,
    album_id: 1,
    kind: "image",
    extension: "jpg",
    title: "Book cover",
    file_url: "book1.jpg",
    rank: 1,
    created_at: null,
  },
];
