#pragma checksum "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4F75FBFEB61F99F6A22E101B0DA7DACCDA053F18"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_Default : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 15 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
    protected global::System.Web.UI.WebControls.TextBox TextBox1;
    
    #line default
    #line hidden
    
    
    #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
    protected global::System.Web.UI.WebControls.ImageButton ImageButton1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 306 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 312 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 319 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 307 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 311 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 317 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 310 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 314 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 315 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 309 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 318 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 305 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 313 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 308 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 323 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_default_aspx : global::Admin_Default, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_default_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/admin/Default.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_default_aspx.@__initialized == false)) {
                global::ASP.admin_default_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/admin/Default.aspx";
                dependencies[1] = "~/admin/admin.master";
                dependencies[2] = "~/admin/admin.master.cs";
                dependencies[3] = "~/admin/Default.aspx.cs";
                global::ASP.admin_default_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_default_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlTextBox1() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 15 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.TextBox1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 15 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl.ID = "TextBox1";
            
            #line default
            #line hidden
            
            #line 15 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl.CssClass = "typehead span8";
            
            #line default
            #line hidden
            
            #line 15 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl.TextChanged += new System.EventHandler(this.TextBox1_TextChanged);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControlImageButton1() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            this.ImageButton1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl.ID = "ImageButton1";
            
            #line default
            #line hidden
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl.ImageUrl = "~/Admin/ara2.png";
            
            #line default
            #line hidden
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(13D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl.Click += new System.Web.UI.ImageClickEventHandler(this.ImageButton1_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(0, 397, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl1 = this.@__BuildControlTextBox1();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl2;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl2 = this.@__BuildControlImageButton1();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(397, 411, true));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_default_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl.MasterPageFile = "~/Admin/admin.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\Default.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.admin_default_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_default_aspx.@__fileDependencies);
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -792876493;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
