#pragma checksum "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A8C30E8E910361A6A9FB002E8B12CCE0603183ED"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_Default : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 26 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.Label lblHata;
    
    #line default
    #line hidden
    
    
    #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlAlert;
    
    #line default
    #line hidden
    
    
    #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtTypeAd;
    
    #line default
    #line hidden
    
    
    #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtBaslik;
    
    #line default
    #line hidden
    
    
    #line 47 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtIcerik;
    
    #line default
    #line hidden
    
    
    #line 54 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtOzet;
    
    #line default
    #line hidden
    
    
    #line 62 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtChck1;
    
    #line default
    #line hidden
    
    
    #line 69 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtChck2;
    
    #line default
    #line hidden
    
    
    #line 76 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal1;
    
    #line default
    #line hidden
    
    
    #line 83 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal2;
    
    #line default
    #line hidden
    
    
    #line 90 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal3;
    
    #line default
    #line hidden
    
    
    #line 97 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal4;
    
    #line default
    #line hidden
    
    
    #line 104 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal5;
    
    #line default
    #line hidden
    
    
    #line 111 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal6;
    
    #line default
    #line hidden
    
    
    #line 118 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal7;
    
    #line default
    #line hidden
    
    
    #line 125 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.CheckBox chckCoverPhoto;
    
    #line default
    #line hidden
    
    
    #line 134 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.CheckBox chckSubImages;
    
    #line default
    #line hidden
    
    
    #line 141 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.CheckBox chckSubFiles;
    
    #line default
    #line hidden
    
    
    #line 148 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.CheckBox chckCategories;
    
    #line default
    #line hidden
    
    
    #line 155 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.CheckBox chckEtiket;
    
    #line default
    #line hidden
    
    
    #line 162 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.CheckBox chckProtected;
    
    #line default
    #line hidden
    
    
    #line 168 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    protected global::System.Web.UI.WebControls.Button btnGonder;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 306 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 312 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 319 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 307 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 311 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 317 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 310 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 314 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 315 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 309 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 318 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 305 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 313 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 308 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 323 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_type_aspx : global::Admin_Default, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_type_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/admin/type.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_type_aspx.@__initialized == false)) {
                global::ASP.admin_type_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/admin/type.aspx";
                dependencies[1] = "~/admin/admin.master";
                dependencies[2] = "~/admin/admin.master.cs";
                dependencies[3] = "~/admin/type.aspx.cs";
                global::ASP.admin_type_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_type_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblHata() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 26 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblHata = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 26 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "lblHata";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlAlert() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlAlert = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "pnlAlert";
            
            #line default
            #line hidden
            
            #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(0, 298, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl1 = this.@__BuildControllblHata();
            
            #line default
            #line hidden
            
            #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </div>\r\n                                "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtTypeAd() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtTypeAd = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtTypeAd";
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtBaslik() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtBaslik = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtBaslik";
            
            #line default
            #line hidden
            
            #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtIcerik() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 47 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtIcerik = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 47 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtIcerik";
            
            #line default
            #line hidden
            
            #line 47 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtOzet() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 54 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtOzet = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 54 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtOzet";
            
            #line default
            #line hidden
            
            #line 54 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtChck1() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 62 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtChck1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 62 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtChck1";
            
            #line default
            #line hidden
            
            #line 62 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtChck2() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 69 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtChck2 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 69 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtChck2";
            
            #line default
            #line hidden
            
            #line 69 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal1() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 76 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 76 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtVal1";
            
            #line default
            #line hidden
            
            #line 76 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal2() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 83 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal2 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 83 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtVal2";
            
            #line default
            #line hidden
            
            #line 83 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal3() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 90 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal3 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 90 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtVal3";
            
            #line default
            #line hidden
            
            #line 90 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal4() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 97 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal4 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 97 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtVal4";
            
            #line default
            #line hidden
            
            #line 97 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal5() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 104 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal5 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 104 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtVal5";
            
            #line default
            #line hidden
            
            #line 104 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal6() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 111 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal6 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 111 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtVal6";
            
            #line default
            #line hidden
            
            #line 111 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal7() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 118 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal7 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 118 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "txtVal7";
            
            #line default
            #line hidden
            
            #line 118 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchckCoverPhoto() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 125 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.chckCoverPhoto = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 125 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "chckCoverPhoto";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchckSubImages() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 134 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.chckSubImages = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 134 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "chckSubImages";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchckSubFiles() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 141 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.chckSubFiles = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 141 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "chckSubFiles";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchckCategories() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 148 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.chckCategories = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 148 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "chckCategories";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchckEtiket() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 155 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.chckEtiket = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 155 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "chckEtiket";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchckProtected() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 162 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.chckProtected = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 162 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "chckProtected";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnGonder() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 168 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnGonder = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 168 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.ID = "btnGonder";
            
            #line default
            #line hidden
            
            #line 168 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.CssClass = "btn blue";
            
            #line default
            #line hidden
            
            #line 168 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.Text = "Onayla";
            
            #line default
            #line hidden
            
            #line 168 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnGonder_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(298, 536, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl1;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl1 = this.@__BuildControlpnlAlert();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(834, 295, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl2 = this.@__BuildControltxtTypeAd();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(1129, 377, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl3 = this.@__BuildControltxtBaslik();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(1506, 383, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl4 = this.@__BuildControltxtIcerik();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(1889, 376, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl5 = this.@__BuildControltxtOzet();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(2265, 387, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl6 = this.@__BuildControltxtChck1();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(2652, 383, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl7 = this.@__BuildControltxtChck2();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(3035, 381, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl8 = this.@__BuildControltxtVal1();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(3416, 381, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl9;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl9 = this.@__BuildControltxtVal2();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(3797, 381, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl10 = this.@__BuildControltxtVal3();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(4178, 381, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl11;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl11 = this.@__BuildControltxtVal4();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(4559, 381, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl12;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl12 = this.@__BuildControltxtVal5();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(4940, 381, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl13;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl13 = this.@__BuildControltxtVal6();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(5321, 381, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl14 = this.@__BuildControltxtVal7();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(5702, 427, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl15;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl15 = this.@__BuildControlchckCoverPhoto();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(6129, 424, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl16;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl16 = this.@__BuildControlchckSubImages();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(6553, 384, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl17;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl17 = this.@__BuildControlchckSubFiles();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(6937, 388, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl18;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl18 = this.@__BuildControlchckCategories();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(7325, 386, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl19;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl19 = this.@__BuildControlchckEtiket();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(7711, 396, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl20;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl20 = this.@__BuildControlchckProtected();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl20);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </div>\r\n                                </d" +
                        "iv>\r\n\r\n                                <div class=\"form_row\">\r\n                 " +
                        "                   <div class=\"field\">\r\n                                        " +
                        ""));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl21;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl21 = this.@__BuildControlbtnGonder();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(@__ctrl21);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(8107, 256, true));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_type_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.MasterPageFile = "~/Admin/admin.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\type.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.admin_type_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_type_aspx.@__fileDependencies);
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1898184313;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
