#pragma checksum "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0A8D9D0D0C0DD8D4B7708993E48C2270B8DCF94E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_Default : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 58 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlDelete;
    
    #line default
    #line hidden
    
    
    #line 65 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlAdded;
    
    #line default
    #line hidden
    
    
    #line 88 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
    protected global::System.Web.UI.WebControls.Repeater rptUrunler;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 306 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 312 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 319 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 307 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 311 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 317 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 310 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 314 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 315 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 309 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 318 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 305 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 313 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 308 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 323 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_ayar_aspx : global::Admin_Default, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_ayar_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/admin/ayar.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_ayar_aspx.@__initialized == false)) {
                global::ASP.admin_ayar_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/admin/ayar.aspx";
                dependencies[1] = "~/admin/admin.master";
                dependencies[2] = "~/admin/admin.master.cs";
                dependencies[3] = "~/admin/ayar.aspx.cs";
                global::ASP.admin_ayar_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_ayar_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderContent1));
        }
        
        private void @__RenderContent1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.WriteUTF8ResourceString(@__w, 1236, 376, true);
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
                                                      Response.Write(_map); 
            
            #line default
            #line hidden
            this.WriteUTF8ResourceString(@__w, 1612, 727, true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlDelete() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 58 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlDelete = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 58 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl.ID = "pnlDelete";
            
            #line default
            #line hidden
            
            #line 58 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 58 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(2339, 333, true));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlAdded() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 65 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlAdded = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 65 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl.ID = "pnlAdded";
            
            #line default
            #line hidden
            
            #line 65 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 65 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(2672, 347, false));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control3() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 91 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(6, 5);
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                                            <tr>\r\n                             " +
                    "                   <td class=\"ayarname\" style=\"display: none\" data=\"");
            @__ctrl.SetStaticString(1, "\"></td>\r\n                                                <td>\r\n                  " +
                    "                                  ");
            @__ctrl.SetStaticString(2, "\r\n                                                </td>\r\n                        " +
                    "                        <td class=\"ayarvalue\">\r\n                                " +
                    "                    <input id=\"title\" class=\"");
            @__ctrl.SetStaticString(3, "\" type=\"text\" value=\"");
            @__ctrl.SetStaticString(4, "\">\r\n\r\n                                                    ");
            @__ctrl.SetStaticString(5, @"
                                                  
                                                </td>
                                                <td>
                                                    <a href="""" class=""ayarduzenle""><span class=""label label-success"">Kaydet</span></a>
                                                    <span class=""label label-success duzenlendi"" style=""display: none"">Başarıyla kaydedildi.</span>
                                                </td>
                                            </tr>
                                        ");
            
            #line 91 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control3);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBind__control3(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.RepeaterItem Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 91 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 91 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 91 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            target.SetDataBoundString(0, global::System.Convert.ToString(Eval("OptionName"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 93 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            target.SetDataBoundString(1, global::System.Convert.ToString(Eval("OptionAd"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 96 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            target.SetDataBoundString(2, global::System.Convert.ToString(Eval("OptionName"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 96 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            target.SetDataBoundString(3, global::System.Convert.ToString(Eval("OptionValue"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 98 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            target.SetDataBoundString(4, global::System.Convert.ToString((Eval("OptionName").ToString()=="map") ? "<div id='map-canvas' style='width:500px;height:300px;'></div><a href='#' onclick='kordinatal()' > kordinati al</a>":"", global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            
            #line 88 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 88 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Repeater @__BuildControlrptUrunler() {
            global::System.Web.UI.WebControls.Repeater @__ctrl;
            
            #line 88 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Repeater();
            
            #line default
            #line hidden
            this.rptUrunler = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 88 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl.ID = "rptUrunler";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(3019, 374, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl1;
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl1 = this.@__BuildControlpnlDelete();
            
            #line default
            #line hidden
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl2;
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl2 = this.@__BuildControlpnlAdded();
            
            #line default
            #line hidden
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(3393, 783, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Repeater @__ctrl3;
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl3 = this.@__BuildControlrptUrunler();
            
            #line default
            #line hidden
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </tbody>\r\n                            </table>\r" +
                        "\n                        </div>\r\n                    </div>\r\n                </d" +
                        "iv>\r\n            </div>\r\n        </div>\r\n    </div>\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_ayar_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl.MasterPageFile = "~/Admin/admin.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\ayar.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.admin_ayar_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_ayar_aspx.@__fileDependencies);
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -2112088976;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
