#pragma checksum "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9D8B4D19FF94E98FFA76C6E4DF49F520C72B9704"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_Default2 : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 14 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    protected global::System.Web.UI.WebControls.Label lblStep;
    
    #line default
    #line hidden
    
    
    #line 23 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    protected global::System.Web.UI.WebControls.Label lblHata;
    
    #line default
    #line hidden
    
    
    #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlAlert;
    
    #line default
    #line hidden
    
    
    #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    protected global::System.Web.UI.WebControls.Label lblSuccess;
    
    #line default
    #line hidden
    
    
    #line 28 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlSuccess;
    
    #line default
    #line hidden
    
    
    #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    protected global::System.Web.UI.WebControls.FileUpload fileUpload1;
    
    #line default
    #line hidden
    
    
    #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    protected global::System.Web.UI.WebControls.Button btnGonder;
    
    #line default
    #line hidden
    
    
    #line 46 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    protected global::System.Web.UI.WebControls.Label test;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 306 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 312 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 319 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 307 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 311 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 317 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 310 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 314 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 315 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 309 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 318 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 305 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 313 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 308 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 323 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_file_aspx : global::Admin_Default2, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_file_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/admin/file.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_file_aspx.@__initialized == false)) {
                global::ASP.admin_file_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/admin/file.aspx";
                dependencies[1] = "~/admin/admin.master";
                dependencies[2] = "~/admin/admin.master.cs";
                dependencies[3] = "~/admin/file.aspx.cs";
                global::ASP.admin_file_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_file_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblStep() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 14 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblStep = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 14 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.ID = "lblStep";
            
            #line default
            #line hidden
            
            #line 14 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 14 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("2.ADIM - "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblHata() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 23 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblHata = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 23 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.ID = "lblHata";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlAlert() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlAlert = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.ID = "pnlAlert";
            
            #line default
            #line hidden
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(0, 306, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl1 = this.@__BuildControllblHata();
            
            #line default
            #line hidden
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </div>\r\n                        "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblSuccess() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblSuccess = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.ID = "lblSuccess";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlSuccess() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 28 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlSuccess = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 28 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.ID = "pnlSuccess";
            
            #line default
            #line hidden
            
            #line 28 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 28 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(306, 318, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 28 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl1 = this.@__BuildControllblSuccess();
            
            #line default
            #line hidden
            
            #line 28 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 28 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </div>\r\n                            \r\n             " +
                        "           "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlfileUpload1() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            
            #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            
            #line default
            #line hidden
            this.fileUpload1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.ID = "fileUpload1";
            
            #line default
            #line hidden
            
            #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "file");
            
            #line default
            #line hidden
            
            #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("name", "files[]");
            
            #line default
            #line hidden
            
            #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("multiple", "");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnGonder() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnGonder = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.ID = "btnGonder";
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.CssClass = "btn blue start";
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.Text = "Yükle";
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnGonder_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControltest() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 46 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.test = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 46 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.ID = "test";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl1 = this.@__BuildControllblStep();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl2;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl2 = this.@__BuildControlpnlAlert();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl3;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl3 = this.@__BuildControlpnlSuccess();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.FileUpload @__ctrl4;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl4 = this.@__BuildControlfileUpload1();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl5;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl5 = this.@__BuildControlbtnGonder();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl6;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl6 = this.@__BuildControltest();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderContent2));
        }
        
        private void @__RenderContent2(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.WriteUTF8ResourceString(@__w, 624, 276, true);
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                            İçerik için ");
            
            #line 15 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
                                           Response.Write(_name); 
            
            #line default
            #line hidden
            @__w.Write(" yükleyin.</h1>\r\n                       \r\n\r\n                        ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n\r\n\r\n                        ");
            parameterContainer.Controls[2].RenderControl(@__w);
            this.WriteUTF8ResourceString(@__w, 900, 336, false);
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n                        </span>\r\n                        ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write("\r\n                        ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
                    " </div>\r\n    </div>\r\n");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_file_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.MasterPageFile = "~/Admin/admin.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\file.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.admin_file_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_file_aspx.@__fileDependencies);
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1817958418;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
