#pragma checksum "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A7EED69ABBE2480B2D2CD0A27D544BFE8E8147F9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Default2 : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 30 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtName;
    
    #line default
    #line hidden
    
    
    #line 36 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtMail;
    
    #line default
    #line hidden
    
    
    #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtSifre;
    
    #line default
    #line hidden
    
    
    #line 47 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtSifret;
    
    #line default
    #line hidden
    
    
    #line 51 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtCountry;
    
    #line default
    #line hidden
    
    
    #line 56 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    protected global::System.Web.UI.WebControls.Button btnGonder;
    
    #line default
    #line hidden
    
    
    #line 60 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    protected global::System.Web.UI.WebControls.Label lblSuccess;
    
    #line default
    #line hidden
    
    
    #line 62 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    protected global::System.Web.UI.WebControls.Label lblError;
    
    #line default
    #line hidden
    
    
    #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlSignup;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 306 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 312 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 319 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 307 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 311 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 317 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 310 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 314 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 315 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 309 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 318 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 305 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 313 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 308 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 323 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class signup_aspx : global::Default2, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public signup_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/signup.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.signup_aspx.@__initialized == false)) {
                global::ASP.signup_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/signup.aspx";
                dependencies[1] = "~/MasterPage.master";
                dependencies[2] = "~/MasterPage.master.cs";
                dependencies[3] = "~/signup.aspx.cs";
                global::ASP.signup_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.signup_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 30 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtName = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 30 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.ID = "txtName";
            
            #line default
            #line hidden
            
            #line 30 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "mail");
            
            #line default
            #line hidden
            
            #line 30 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 30 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("required", "");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtMail() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 36 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtMail = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 36 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.ID = "txtMail";
            
            #line default
            #line hidden
            
            #line 36 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "mail");
            
            #line default
            #line hidden
            
            #line 36 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 36 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("required", "");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSifre() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtSifre = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.ID = "txtSifre";
            
            #line default
            #line hidden
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "password");
            
            #line default
            #line hidden
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("required", "");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSifret() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 47 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtSifret = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 47 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.ID = "txtSifret";
            
            #line default
            #line hidden
            
            #line 47 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "password");
            
            #line default
            #line hidden
            
            #line 47 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 47 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("required", "");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtCountry() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 51 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtCountry = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 51 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.ID = "txtCountry";
            
            #line default
            #line hidden
            
            #line 51 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "mail");
            
            #line default
            #line hidden
            
            #line 51 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 51 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("required", "");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnGonder() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 56 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnGonder = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 56 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.ID = "btnGonder";
            
            #line default
            #line hidden
            
            #line 56 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.CssClass = "btn btn-default";
            
            #line default
            #line hidden
            
            #line 56 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.Text = "Create my account";
            
            #line default
            #line hidden
            
            #line 56 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnGonder_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblSuccess() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 60 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblSuccess = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 60 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.ID = "lblSuccess";
            
            #line default
            #line hidden
            
            #line 60 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.CssClass = "success";
            
            #line default
            #line hidden
            
            #line 60 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            
            #line 60 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.ForeColor = ((System.Drawing.Color)(global::System.Drawing.Color.FromArgb(51, 204, 51)));
            
            #line default
            #line hidden
            
            #line 60 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.Font.Bold = true;
            
            #line default
            #line hidden
            
            #line 60 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.Text = "Thanks for Registering! <a href=\'login\'>Click Login</a>";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblError() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 62 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblError = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 62 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.ID = "lblError";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlSignup() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlSignup = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.ID = "pnlSignup";
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.DefaultButton = "btnGonder";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(0, 398, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl1 = this.@__BuildControltxtName();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </div>\r\n\r\n\r\n                                <di" +
                        "v class=\"form-group\">\r\n                                    <label>Email Address " +
                        "<span class=\"required\">*</span></label>\r\n                                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl2 = this.@__BuildControltxtMail();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </div>\r\n\r\n                                <div " +
                        "class=\"form-group\">\r\n                                    <label>Password: <span " +
                        "class=\"required\">*</span></label>\r\n                                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl3 = this.@__BuildControltxtSifre();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </div>\r\n\r\n\r\n                                <di" +
                        "v class=\"form-group\">\r\n                                    <label>Password Again" +
                        ": <span class=\"required\">*</span></label>\r\n                                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl4 = this.@__BuildControltxtSifret();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </div>\r\n                                <div cl" +
                        "ass=\"form-group\">\r\n                                    <label>Country <span clas" +
                        "s=\"required\">*</span></label>\r\n                                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl5 = this.@__BuildControltxtCountry();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </div>\r\n\r\n\r\n                                <di" +
                        "v class=\"buttons-box clearfix\">\r\n                                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl6;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl6 = this.@__BuildControlbtnGonder();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    <br />\r\n                                   " +
                        " <br />\r\n\r\n                                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl7;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl7 = this.@__BuildControllblSuccess();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                      \r\n                                    <sp" +
                        "an class=\"required\">"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl8;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl8 = this.@__BuildControllblError();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</span>\r\n                                </div>\r\n                                " +
                        "<!-- .form-box -->\r\n                                    "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(398, 653, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl1;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl1 = this.@__BuildControlpnlSignup();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            </div>\r\n                        </div>\r\n           " +
                        "         </div>\r\n                </div>\r\n            </div>\r\n            <!-- .c" +
                        "ontainer -->\r\n        </section>\r\n        <!-- #main -->\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(signup_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.MasterPageFile = "~/MasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\signup.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.signup_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.signup_aspx.@__fileDependencies);
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -2133192609;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
