#pragma checksum "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0B94929878F2379B4E1CA39358D95537AA39A9E6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_Default2 : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
    protected global::System.Web.UI.WebControls.Repeater rptAlbum;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 306 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 312 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 319 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 307 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 311 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 317 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 310 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 314 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 315 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 309 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 318 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 305 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 313 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 308 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 323 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_files_aspx : global::Admin_Default2, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_files_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/admin/files.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_files_aspx.@__initialized == false)) {
                global::ASP.admin_files_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/admin/files.aspx";
                dependencies[1] = "~/admin/admin.master";
                dependencies[2] = "~/admin/admin.master.cs";
                dependencies[3] = "~/admin/files.aspx.cs";
                global::ASP.admin_files_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_files_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control3() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(8, 7);
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                            <li class=\"span3 relative album left notmodified\" d" +
                    "ata-id=\"");
            @__ctrl.SetStaticString(1, "\" style=\"background-image:url(\'");
            @__ctrl.SetStaticString(2, "\');\">\r\n\r\n                                <a href=\"../Dosyalar/orjinal/");
            @__ctrl.SetStaticString(3, "\" target=\"_blank\" class=\"rightbottom\" title=\"");
            @__ctrl.SetStaticString(4, "\" style=\"right:92px;max-width:90px;padding:0px 2px;overflow:hidden\"><span class=\"" +
                    "label label-success\" style=\"float:right\">");
            @__ctrl.SetStaticString(5, "</span></a>\r\n                                <a href=\"file.aspx?id=");
            @__ctrl.SetStaticString(6, "&t=file\" class=\"rightbottom\" style=\"right: 30px\"><span class=\"label label-success" +
                    "\">Düzenle</span></a>\r\n                                <a href=\"_sil.aspx?id=");
            @__ctrl.SetStaticString(7, "&t=file\" class=\"eminmisin rightbottom\"><span class=\"label label-success\">Sil</spa" +
                    "n></a>\r\n                            </li>\r\n                        ");
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control3);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBind__control3(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.RepeaterItem Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            target.SetDataBoundString(0, global::System.Convert.ToString(Eval("FileId"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            target.SetDataBoundString(1, global::System.Convert.ToString(icon(Eval("FileUrl"),Eval("Tur"),Eval("Ext")), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            target.SetDataBoundString(2, global::System.Convert.ToString(Eval("FileUrl"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            target.SetDataBoundString(3, global::System.Convert.ToString(Eval("FileTitle"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            target.SetDataBoundString(4, global::System.Convert.ToString(Eval("FileTitle"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 34 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            target.SetDataBoundString(5, global::System.Convert.ToString(Eval("FileId"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 35 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            target.SetDataBoundString(6, global::System.Convert.ToString(Eval("FileId"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Repeater @__BuildControlrptAlbum() {
            global::System.Web.UI.WebControls.Repeater @__ctrl;
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Repeater();
            
            #line default
            #line hidden
            this.rptAlbum = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__ctrl.ID = "rptAlbum";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.WebControls.Repeater @__ctrl1;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__ctrl1 = this.@__BuildControlrptAlbum();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderContent2));
        }
        
        private void @__RenderContent2(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.WriteUTF8ResourceString(@__w, 1101, 535, true);
            
            #line 19 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
                                                      @__w.Write( Request["id"].ToString());

            
            #line default
            #line hidden
            @__w.Write("&tur=");
            
            #line 19 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
                                                                                         @__w.Write( (Request["tur"].ToString()=="file")? "file":"image" );

            
            #line default
            #line hidden
            this.WriteUTF8ResourceString(@__w, 1636, 324, true);
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                </ul>\r\n            </div>\r\n    </div>\r\n    </div>\r\n");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_files_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__ctrl.MasterPageFile = "~/Admin/admin.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\files.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.admin_files_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_files_aspx.@__fileDependencies);
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1536225024;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
