#pragma checksum "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B0970ED20D856992C0F002B52481566CB3CCCDD0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class _Default : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
    protected global::System.Web.UI.WebControls.Repeater rptBlogCategories;
    
    #line default
    #line hidden
    
    
    #line 43 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
    protected global::System.Web.UI.WebControls.Repeater rptBlogs;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 306 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 312 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 319 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 307 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 311 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 317 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 310 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 314 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 315 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 309 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 318 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 305 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 313 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 308 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 323 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class blogs_aspx : global::_Default, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public blogs_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/blogs.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.blogs_aspx.@__initialized == false)) {
                global::ASP.blogs_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/blogs.aspx";
                dependencies[1] = "~/MasterPage.master";
                dependencies[2] = "~/MasterPage.master.cs";
                dependencies[3] = "~/blogs.aspx.cs";
                global::ASP.blogs_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.blogs_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control3() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(3, 2);
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                                <li><a href=\"#\" style=\"color: #000;\" data-filte" +
                    "r=\".filter");
            @__ctrl.SetStaticString(1, "\">");
            @__ctrl.SetStaticString(2, "</a></li>\r\n                                    ");
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control3);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBind__control3(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.RepeaterItem Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            target.SetDataBoundString(0, global::System.Convert.ToString(Eval("CatId"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            target.SetDataBoundString(1, global::System.Convert.ToString(Eval("CatName"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Repeater @__BuildControlrptBlogCategories() {
            global::System.Web.UI.WebControls.Repeater @__ctrl;
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Repeater();
            
            #line default
            #line hidden
            this.rptBlogCategories = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            
            #line default
            #line hidden
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl.ID = "rptBlogCategories";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control5() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(6, 5);
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                            <div class=\"work-element filter");
            @__ctrl.SetStaticString(1, " col-xs-12 col-sm-3 col-md-3\">\r\n                                <a href=\"i/");
            @__ctrl.SetStaticString(2, "-");
            @__ctrl.SetStaticString(3, "\" class=\"work\">\r\n                                    <img src=\"Dosyalar/orta/");
            @__ctrl.SetStaticString(4, @""" width=""270"" height=""197"" alt="""">
                                    <span class=""shadow""></span>
                                    <div class=""bg-hover""></div>
                                    <div class=""work-title"">
                                        <h3 class=""title"">");
            @__ctrl.SetStaticString(5, "</h3>\r\n                                    </div>\r\n                              " +
                    "  </a>\r\n                            </div>\r\n                           ");
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control5);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBind__control5(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.RepeaterItem Container;
            System.Web.UI.DataBoundLiteralControl target;
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            Container = ((System.Web.UI.WebControls.RepeaterItem)(target.BindingContainer));
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            target.SetDataBoundString(0, global::System.Convert.ToString(Eval("CatId"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 45 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            target.SetDataBoundString(1, global::System.Convert.ToString(Eval("PageId"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 45 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            target.SetDataBoundString(2, global::System.Convert.ToString(htmluret(Eval("PageTitle")), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 46 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            target.SetDataBoundString(3, global::System.Convert.ToString(Eval("PictureUrl"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
            
            #line 50 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            target.SetDataBoundString(4, global::System.Convert.ToString(Eval("PageTitle"), global::System.Globalization.CultureInfo.CurrentCulture));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control4(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            
            #line 43 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl1 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 43 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Repeater @__BuildControlrptBlogs() {
            global::System.Web.UI.WebControls.Repeater @__ctrl;
            
            #line 43 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Repeater();
            
            #line default
            #line hidden
            this.rptBlogs = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 43 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control4));
            
            #line default
            #line hidden
            
            #line 43 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl.ID = "rptBlogs";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(905, 1085, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Repeater @__ctrl1;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl1 = this.@__BuildControlrptBlogCategories();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(1990, 352, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Repeater @__ctrl2;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl2 = this.@__BuildControlrptBlogs();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                    </div>\r\n                </d" +
                        "iv>\r\n            </div>\r\n            <!-- .full-width-box -->\r\n\r\n\r\n\r\n\r\n\r\n       " +
                        " </article>\r\n    </section>\r\n    <!-- #main -->\r\n\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(blogs_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl.MasterPageFile = "~/MasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\blogs.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.blogs_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.blogs_aspx.@__fileDependencies);
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -385948320;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
