#pragma checksum "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "CCCBF47328F1CBFB7147600C7A62EEA9DB4473D4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_login : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
    protected global::System.Web.UI.WebControls.Label lbl1;
    
    #line default
    #line hidden
    
    
    #line 43 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtUser;
    
    #line default
    #line hidden
    
    
    #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtSifre;
    
    #line default
    #line hidden
    
    
    #line 52 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
    protected global::System.Web.UI.WebControls.Button Button1;
    
    #line default
    #line hidden
    
    
    #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 311 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 318 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 309 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 307 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 313 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 323 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 314 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 310 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 305 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 312 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 319 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 315 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 306 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 308 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 317 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_login_aspx : global::Admin_login, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_login_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/admin/login.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_login_aspx.@__initialized == false)) {
                global::ASP.admin_login_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/admin/login.aspx";
                dependencies[1] = "~/admin/login.aspx.cs";
                global::ASP.admin_login_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_login_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("charset", "utf-8");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 8 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 8 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Yönetim Paneli"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 9 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Name = "viewport";
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Content = "width=device-width, initial-scale=1.0";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 10 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 10 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Name = "description";
            
            #line default
            #line hidden
            
            #line 10 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Content = "";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control7() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 11 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 11 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Name = "author";
            
            #line default
            #line hidden
            
            #line 11 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Content = "";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control8() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 14 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 14 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Href = "css/bootstrap.css";
            
            #line default
            #line hidden
            
            #line 14 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control9() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 15 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 15 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Href = "css/bootstrap-responsive.css";
            
            #line default
            #line hidden
            
            #line 15 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 16 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 16 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Href = "css/stylesheet.css";
            
            #line default
            #line hidden
            
            #line 16 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control11() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 17 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 17 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Href = "icon/font-awesome.css";
            
            #line default
            #line hidden
            
            #line 17 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control12() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Href = "http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800";
            
            #line default
            #line hidden
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 18 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control13() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 21 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 21 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "apple-touch-icon-precomposed");
            
            #line default
            #line hidden
            
            #line 21 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("sizes", "144x144");
            
            #line default
            #line hidden
            
            #line 21 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Href = "img/apple-touch-icon-144-precomposed.html";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control14() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "apple-touch-icon-precomposed");
            
            #line default
            #line hidden
            
            #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("sizes", "114x114");
            
            #line default
            #line hidden
            
            #line 22 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Href = "img/apple-touch-icon-114-precomposed.html";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control15() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 23 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 23 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "apple-touch-icon-precomposed");
            
            #line default
            #line hidden
            
            #line 23 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("sizes", "72x72");
            
            #line default
            #line hidden
            
            #line 23 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Href = "img/apple-touch-icon-72-precomposed.html";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control16() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "apple-touch-icon-precomposed");
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Href = "img/apple-touch-icon-57-precomposed.html";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control17() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 25 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 25 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "shortcut icon");
            
            #line default
            #line hidden
            
            #line 25 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Href = "img/favicon.png";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl1;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl2;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl3;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl4;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl4 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl5;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl5 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    <!-- Le styles -->\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl6;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl6 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl7;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl7 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl8;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl8 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl9;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl9 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl10;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl10 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    <!-- Le fav and touch icons -->\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl11;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl11 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl12;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl12 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl13;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl13 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl14;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl14 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl15;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl15 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n    <!--[if lt " +
                        "IE 9]>\r\n      <script src=\"js/html5shiv.js\"></script>\r\n    <![endif]-->\r\n"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllbl1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lbl1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.ID = "lbl1";
            
            #line default
            #line hidden
            
            #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Text = "Bilgileriniz Hatalı";
            
            #line default
            #line hidden
            
            #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtUser() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 43 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtUser = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 43 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.ID = "txtUser";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSifre() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtSifre = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.ID = "txtSifre";
            
            #line default
            #line hidden
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlButton1() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 52 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.Button1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 52 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.ID = "Button1";
            
            #line default
            #line hidden
            
            #line 52 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Text = "TAMAM";
            
            #line default
            #line hidden
            
            #line 52 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.CssClass = "pull-right btn btn-large blue";
            
            #line default
            #line hidden
            
            #line 52 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.Click += new System.EventHandler(this.Button1_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    \r\n    <div class=\"login-container\">\r\n        <div class=\"login-header borde" +
                        "red\">\r\n           <img src=\"img/logogiris.png\" />\r\n        </div>\r\n        <form" +
                        ">\r\n            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl1 = this.@__BuildControllbl1();
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            <div class=\"login-field\">\r\n                <label for=\"username\">Pe" +
                        "rsonel Adı</label>\r\n                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl2 = this.@__BuildControltxtUser();
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                <i class=\"icon-user\"></i>\r\n            </div>\r\n            <div" +
                        " class=\"login-field\">\r\n                <label for=\"password\">Şifre</label>\r\n    " +
                        "            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl3 = this.@__BuildControltxtSifre();
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                <i class=\"icon-lock\"></i>\r\n            </div>\r\n            <div" +
                        " class=\"login-button clearfix\">\r\n        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl4;
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl4 = this.@__BuildControlButton1();
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(6915, 2872, true));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_login_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<body>\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\login.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.admin_login_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_login_aspx.@__fileDependencies);
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1173346161;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
