#pragma checksum "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "C0FD67C1EE6D972303DC613DCCE8338E8336A2C6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_Default2 : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    protected global::System.Web.UI.WebControls.Label lblHata;
    
    #line default
    #line hidden
    
    
    #line 19 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlAlert;
    
    #line default
    #line hidden
    
    
    #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtAd;
    
    #line default
    #line hidden
    
    
    #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    protected global::System.Web.UI.WebControls.FileUpload fl1;
    
    #line default
    #line hidden
    
    
    #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    protected global::System.Web.UI.WebControls.DropDownList drpTypes;
    
    #line default
    #line hidden
    
    
    #line 55 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    protected global::System.Web.UI.WebControls.Button btnGonder;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 306 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 312 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 319 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 307 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 311 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 317 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 310 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 314 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 315 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 309 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 318 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 305 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 313 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 308 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 323 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_kategori_aspx : global::Admin_Default2, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_kategori_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/admin/kategori.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_kategori_aspx.@__initialized == false)) {
                global::ASP.admin_kategori_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/admin/kategori.aspx";
                dependencies[1] = "~/admin/admin.master";
                dependencies[2] = "~/admin/admin.master.cs";
                dependencies[3] = "~/admin/kategori.aspx.cs";
                global::ASP.admin_kategori_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_kategori_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblHata() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblHata = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.ID = "lblHata";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlAlert() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 19 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlAlert = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 19 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.ID = "pnlAlert";
            
            #line default
            #line hidden
            
            #line 19 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 19 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(0, 344, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 19 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl1 = this.@__BuildControllblHata();
            
            #line default
            #line hidden
            
            #line 19 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 19 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </div>\r\n                                "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtAd() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtAd = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.ID = "txtAd";
            
            #line default
            #line hidden
            
            #line 31 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlfl1() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            
            #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            
            #line default
            #line hidden
            this.fl1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 40 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.ID = "fl1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpTypes() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.drpTypes = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 48 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.ID = "drpTypes";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnGonder() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 55 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnGonder = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 55 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.ID = "btnGonder";
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.Text = "Kaydet";
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.CssClass = "btn blue";
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnGonder_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(344, 585, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl1;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl1 = this.@__BuildControlpnlAlert();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(929, 336, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl2 = this.@__BuildControltxtAd();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(1265, 462, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.FileUpload @__ctrl3;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl3 = this.@__BuildControlfl1();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(1727, 422, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl4;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl4 = this.@__BuildControldrpTypes();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                 </div>\r\n                                </di" +
                        "v>\r\n                                <div class=\"form_row\">\r\n                    " +
                        "                <div class=\"field\">\r\n                                        "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl5;
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl5 = this.@__BuildControlbtnGonder();
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </div>\r\n                                </d" +
                        "iv>\r\n                            </div>\r\n                        </div>\r\n       " +
                        "             </div>\r\n                </div>\r\n            </div>\r\n        </div>\r" +
                        "\n    </div>\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_kategori_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.MasterPageFile = "~/Admin/admin.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 4 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 6 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\kategori.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.admin_kategori_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_kategori_aspx.@__fileDependencies);
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1731773571;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
