#pragma checksum "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "35D4F1A6FCF4A3F67A6DCFF34318C2F39B8CF1B9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_Default : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 28 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Label lblHata;
    
    #line default
    #line hidden
    
    
    #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlAlert;
    
    #line default
    #line hidden
    
    
    #line 35 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.DropDownList drpKategoriler;
    
    #line default
    #line hidden
    
    
    #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlKategori;
    
    #line default
    #line hidden
    
    
    #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.DropDownList drpDiller;
    
    #line default
    #line hidden
    
    
    #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlDiller;
    
    #line default
    #line hidden
    
    
    #line 53 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtBaslik;
    
    #line default
    #line hidden
    
    
    #line 50 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlTitle;
    
    #line default
    #line hidden
    
    
    #line 60 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.FileUpload fl1;
    
    #line default
    #line hidden
    
    
    #line 57 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlPicture;
    
    #line default
    #line hidden
    
    
    #line 67 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtOzet;
    
    #line default
    #line hidden
    
    
    #line 64 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlSummary;
    
    #line default
    #line hidden
    
    
    #line 74 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.CheckBox chck1;
    
    #line default
    #line hidden
    
    
    #line 71 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlChck1;
    
    #line default
    #line hidden
    
    
    #line 81 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.CheckBox chck2;
    
    #line default
    #line hidden
    
    
    #line 78 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlChck2;
    
    #line default
    #line hidden
    
    
    #line 88 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal1;
    
    #line default
    #line hidden
    
    
    #line 85 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlVal1;
    
    #line default
    #line hidden
    
    
    #line 95 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal2;
    
    #line default
    #line hidden
    
    
    #line 92 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlVal2;
    
    #line default
    #line hidden
    
    
    #line 102 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal3;
    
    #line default
    #line hidden
    
    
    #line 99 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlVal3;
    
    #line default
    #line hidden
    
    
    #line 110 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal4;
    
    #line default
    #line hidden
    
    
    #line 107 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlVal4;
    
    #line default
    #line hidden
    
    
    #line 118 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal5;
    
    #line default
    #line hidden
    
    
    #line 115 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlVal5;
    
    #line default
    #line hidden
    
    
    #line 126 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal6;
    
    #line default
    #line hidden
    
    
    #line 123 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlVal6;
    
    #line default
    #line hidden
    
    
    #line 134 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtVal7;
    
    #line default
    #line hidden
    
    
    #line 131 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlVal7;
    
    #line default
    #line hidden
    
    
    #line 143 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtIcerik;
    
    #line default
    #line hidden
    
    
    #line 139 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlText;
    
    #line default
    #line hidden
    
    
    #line 150 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtTags;
    
    #line default
    #line hidden
    
    
    #line 147 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlEtiketler;
    
    #line default
    #line hidden
    
    
    #line 157 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    protected global::System.Web.UI.WebControls.Button btnGonder;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 306 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 312 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 319 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 307 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 311 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 317 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 310 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 314 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 315 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 309 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 318 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 305 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 313 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 308 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 323 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_icerik_aspx : global::Admin_Default, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_icerik_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/admin/icerik.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_icerik_aspx.@__initialized == false)) {
                global::ASP.admin_icerik_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/admin/icerik.aspx";
                dependencies[1] = "~/admin/admin.master";
                dependencies[2] = "~/admin/admin.master.cs";
                dependencies[3] = "~/admin/icerik.aspx.cs";
                global::ASP.admin_icerik_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_icerik_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblHata() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 28 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblHata = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 28 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "lblHata";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlAlert() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlAlert = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlAlert";
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(0, 298, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl1;
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControllblHata();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    </div>\r\n                                "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpKategoriler() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 35 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.drpKategoriler = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 35 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "drpKategoriler";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlKategori() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlKategori = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlKategori";
            
            #line default
            #line hidden
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        <label class=\"field_name align_right\">K" +
                        "ategori <span class=\"required\">*</span></label>\r\n                               " +
                        "         <div class=\"field\">\r\n                                            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControldrpKategoriler();
            
            #line default
            #line hidden
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 32 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        </div>\r\n                               " +
                        " "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControldrpDiller() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.drpDiller = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 44 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "drpDiller";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlDiller() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlDiller = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlDiller";
            
            #line default
            #line hidden
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        <label class=\"field_name align_right\">D" +
                        "iller <span class=\"required\">*</span></label>\r\n                                 " +
                        "       <div class=\"field\">\r\n                                            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControldrpDiller();
            
            #line default
            #line hidden
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 41 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        </div>\r\n                               " +
                        " "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtBaslik() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 53 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtBaslik = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 53 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "txtBaslik";
            
            #line default
            #line hidden
            
            #line 53 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlTitle() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 50 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlTitle = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 50 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlTitle";
            
            #line default
            #line hidden
            
            #line 50 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 50 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControltxtBaslik();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 50 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlTitle));
            return @__ctrl;
        }
        
        private void @__RenderpnlTitle(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                        <label class=\"field_name align_right\">");
            
            #line 51 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                 Response.Write(_title); 
            
            #line default
            #line hidden
            @__w.Write(" <span class=\"required\">*</span></label>\r\n                                       " +
                    " <div class=\"field\">\r\n                                            ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                        </div>\r\n                               " +
                    " ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlfl1() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            
            #line 60 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            
            #line default
            #line hidden
            this.fl1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 60 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "fl1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlPicture() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 57 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlPicture = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 57 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlPicture";
            
            #line default
            #line hidden
            
            #line 57 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 57 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        <label class=\"field_name align_right\">K" +
                        "apak Fotoğrafı<span class=\"required\">*</span></label>\r\n                         " +
                        "               <div class=\"field\">\r\n                                            " +
                        ""));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.FileUpload @__ctrl1;
            
            #line 57 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControlfl1();
            
            #line default
            #line hidden
            
            #line 57 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 57 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                        </div>\r\n                               " +
                        " "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtOzet() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 67 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtOzet = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 67 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "txtOzet";
            
            #line default
            #line hidden
            
            #line 67 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlSummary() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 64 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlSummary = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 64 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlSummary";
            
            #line default
            #line hidden
            
            #line 64 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 64 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControltxtOzet();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 64 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlSummary));
            return @__ctrl;
        }
        
        private void @__RenderpnlSummary(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                        <label class=\"field_name align_right\">");
            
            #line 65 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                 Response.Write(_summary); 
            
            #line default
            #line hidden
            @__w.Write(" <span class=\"required\">*</span></label>\r\n                                       " +
                    " <div class=\"field\">\r\n                                            ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                        </div>\r\n                               " +
                    " ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchck1() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 74 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.chck1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 74 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "chck1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlChck1() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 71 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlChck1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 71 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlChck1";
            
            #line default
            #line hidden
            
            #line 71 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl1;
            
            #line 71 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControlchck1();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 71 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlChck1));
            return @__ctrl;
        }
        
        private void @__RenderpnlChck1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                        <label class=\"field_name align_right\">");
            
            #line 72 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                 Response.Write(_chck1); 
            
            #line default
            #line hidden
            @__w.Write(" <span class=\"required\">*</span></label>\r\n                                       " +
                    " <div class=\"field\">\r\n                                            ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                        </div>\r\n                               " +
                    " ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchck2() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 81 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.chck2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 81 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "chck2";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlChck2() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 78 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlChck2 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 78 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlChck2";
            
            #line default
            #line hidden
            
            #line 78 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl1;
            
            #line 78 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControlchck2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 78 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlChck2));
            return @__ctrl;
        }
        
        private void @__RenderpnlChck2(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                        <label class=\"field_name align_right\">");
            
            #line 79 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                 Response.Write(_chck2); 
            
            #line default
            #line hidden
            @__w.Write("<span class=\"required\">*</span></label>\r\n                                        " +
                    "<div class=\"field\">\r\n                                            ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                        </div>\r\n                               " +
                    " ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal1() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 88 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 88 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "txtVal1";
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlVal1() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 85 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlVal1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 85 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlVal1";
            
            #line default
            #line hidden
            
            #line 85 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 85 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControltxtVal1();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 85 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlVal1));
            return @__ctrl;
        }
        
        private void @__RenderpnlVal1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                        <label class=\"field_name align_right\">");
            
            #line 86 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                 Response.Write(_val1); 
            
            #line default
            #line hidden
            @__w.Write("<span class=\"required\">*</span></label>\r\n                                        " +
                    "<div class=\"field\">\r\n                                            ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                        </div>\r\n                               " +
                    " ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal2() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 95 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 95 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "txtVal2";
            
            #line default
            #line hidden
            
            #line 95 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlVal2() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 92 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlVal2 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 92 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlVal2";
            
            #line default
            #line hidden
            
            #line 92 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 92 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControltxtVal2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 92 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlVal2));
            return @__ctrl;
        }
        
        private void @__RenderpnlVal2(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                        <label class=\"field_name align_right\">");
            
            #line 93 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                 Response.Write(_val2); 
            
            #line default
            #line hidden
            @__w.Write("<span class=\"required\">*</span></label>\r\n                                        " +
                    "<div class=\"field\">\r\n                                            ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                        </div>\r\n                               " +
                    " ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal3() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 102 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 102 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "txtVal3";
            
            #line default
            #line hidden
            
            #line 102 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlVal3() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 99 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlVal3 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 99 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlVal3";
            
            #line default
            #line hidden
            
            #line 99 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 99 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControltxtVal3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 99 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlVal3));
            return @__ctrl;
        }
        
        private void @__RenderpnlVal3(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                        <label class=\"field_name align_right\">");
            
            #line 100 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                 Response.Write(_val3); 
            
            #line default
            #line hidden
            @__w.Write("<span class=\"required\">*</span></label>\r\n                                        " +
                    "<div class=\"field\">\r\n                                            ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                        </div>\r\n                               " +
                    " ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal4() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 110 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal4 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 110 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "txtVal4";
            
            #line default
            #line hidden
            
            #line 110 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlVal4() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 107 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlVal4 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 107 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlVal4";
            
            #line default
            #line hidden
            
            #line 107 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 107 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControltxtVal4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 107 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlVal4));
            return @__ctrl;
        }
        
        private void @__RenderpnlVal4(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                            <label class=\"field_name align_righ" +
                    "t\">");
            
            #line 108 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                     Response.Write(_val4); 
            
            #line default
            #line hidden
            @__w.Write("<span class=\"required\">*</span></label>\r\n                                        " +
                    "    <div class=\"field\">\r\n                                                ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                            </div>\r\n                           " +
                    "         ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal5() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 118 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal5 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 118 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "txtVal5";
            
            #line default
            #line hidden
            
            #line 118 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlVal5() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 115 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlVal5 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 115 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlVal5";
            
            #line default
            #line hidden
            
            #line 115 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 115 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControltxtVal5();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 115 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlVal5));
            return @__ctrl;
        }
        
        private void @__RenderpnlVal5(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                            <label class=\"field_name align_righ" +
                    "t\">");
            
            #line 116 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                     Response.Write(_val5); 
            
            #line default
            #line hidden
            @__w.Write("<span class=\"required\">*</span></label>\r\n                                        " +
                    "    <div class=\"field\">\r\n                                                ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                            </div>\r\n\r\n                         " +
                    "           ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal6() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 126 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal6 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 126 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "txtVal6";
            
            #line default
            #line hidden
            
            #line 126 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlVal6() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 123 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlVal6 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 123 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlVal6";
            
            #line default
            #line hidden
            
            #line 123 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 123 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControltxtVal6();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 123 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlVal6));
            return @__ctrl;
        }
        
        private void @__RenderpnlVal6(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                            <label class=\"field_name align_righ" +
                    "t\">");
            
            #line 124 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                     Response.Write(_val6); 
            
            #line default
            #line hidden
            @__w.Write("<span class=\"required\">*</span></label>\r\n                                        " +
                    "    <div class=\"field\">\r\n                                                ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                      </div>\r\n\r\n                               " +
                    "     ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtVal7() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 134 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtVal7 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 134 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "txtVal7";
            
            #line default
            #line hidden
            
            #line 134 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "span8";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlVal7() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 131 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlVal7 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 131 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlVal7";
            
            #line default
            #line hidden
            
            #line 131 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 131 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControltxtVal7();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 131 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlVal7));
            return @__ctrl;
        }
        
        private void @__RenderpnlVal7(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                            <label class=\"field_name align_righ" +
                    "t\">");
            
            #line 132 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                     Response.Write(_val7); 
            
            #line default
            #line hidden
            @__w.Write("<span class=\"required\">*</span></label>\r\n                                        " +
                    "    <div class=\"field\">\r\n                                                ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                      </div>\r\n\r\n                               " +
                    "     ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtIcerik() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 143 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtIcerik = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 143 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "txtIcerik";
            
            #line default
            #line hidden
            
            #line 143 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.MultiLine;
            
            #line default
            #line hidden
            
            #line 143 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "...");
            
            #line default
            #line hidden
            
            #line 143 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "width: 100%; height: 300px");
            
            #line default
            #line hidden
            
            #line 143 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "ckeditor");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlText() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 139 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlText = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 139 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlText";
            
            #line default
            #line hidden
            
            #line 139 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 139 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControltxtIcerik();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 139 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderpnlText));
            return @__ctrl;
        }
        
        private void @__RenderpnlText(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n                                            <label class=\"field_name align_righ" +
                    "t\">");
            
            #line 140 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
                                                                                     Response.Write(_text); 
            
            #line default
            #line hidden
            @__w.Write("<span class=\"required\">*</span></label><br /><br />\r\n                            " +
                    "                <div class=\"\">\r\n\r\n                                              " +
                    "  ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n                                            </div>\r\n                           " +
                    "         ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtTags() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 150 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtTags = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 150 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "txtTags";
            
            #line default
            #line hidden
            
            #line 150 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("data-id", "");
            
            #line default
            #line hidden
            
            #line 150 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("data-type", "sayfa");
            
            #line default
            #line hidden
            
            #line 150 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "tags";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlEtiketler() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 147 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlEtiketler = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 147 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "pnlEtiketler";
            
            #line default
            #line hidden
            
            #line 147 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "form_row control-group";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 147 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                            <label class=\"field_name align_righ" +
                        "t\">Etiketler</label>\r\n                                            <div class=\"fi" +
                        "eld checklist\">\r\n                                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 147 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControltxtTags();
            
            #line default
            #line hidden
            
            #line 147 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 147 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                            </div>\r\n                           " +
                        "         "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnGonder() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 157 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnGonder = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 157 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.ID = "btnGonder";
            
            #line default
            #line hidden
            
            #line 157 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.CssClass = "btn blue";
            
            #line default
            #line hidden
            
            #line 157 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.Text = "Onayla";
            
            #line default
            #line hidden
            
            #line 157 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnGonder_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(298, 539, false));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl1;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl1 = this.@__BuildControlpnlAlert();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl2;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl2 = this.@__BuildControlpnlKategori();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl3;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl3 = this.@__BuildControlpnlDiller();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl4;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl4 = this.@__BuildControlpnlTitle();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl5;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl5 = this.@__BuildControlpnlPicture();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl6;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl6 = this.@__BuildControlpnlSummary();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl7;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl7 = this.@__BuildControlpnlChck1();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl8;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl8 = this.@__BuildControlpnlChck2();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl9;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl9 = this.@__BuildControlpnlVal1();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl10;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl10 = this.@__BuildControlpnlVal2();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl11;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl11 = this.@__BuildControlpnlVal3();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n                                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl12;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl12 = this.@__BuildControlpnlVal4();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n                                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl13;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl13 = this.@__BuildControlpnlVal5();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                  "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl14;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl14 = this.@__BuildControlpnlVal6();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl15;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl15 = this.@__BuildControlpnlVal7();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl16;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl16 = this.@__BuildControlpnlText();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                                    "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl17;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl17 = this.@__BuildControlpnlEtiketler();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n                                    <div class=\"form_row\">\r\n               " +
                        "                         <div class=\"field\">\r\n                                  " +
                        "          "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl18;
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl18 = this.@__BuildControlbtnGonder();
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(837, 264, true));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_icerik_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.MasterPageFile = "~/Admin/admin.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\admin\icerik.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.admin_icerik_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_icerik_aspx.@__fileDependencies);
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1038438648;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
