#pragma checksum "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "AE28E987551F8D2FB8F30D373B85C02A64BFC9F5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Default2 : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 23 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    protected global::System.Web.UI.WebControls.Literal ltlIletisim;
    
    #line default
    #line hidden
    
    
    #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtAd;
    
    #line default
    #line hidden
    
    
    #line 35 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtMail;
    
    #line default
    #line hidden
    
    
    #line 37 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtTel;
    
    #line default
    #line hidden
    
    
    #line 39 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtMesaj;
    
    #line default
    #line hidden
    
    
    #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    protected global::System.Web.UI.WebControls.Button btnGonder;
    
    #line default
    #line hidden
    
    
    #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlIletisim;
    
    #line default
    #line hidden
    
    
    #line 46 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    protected global::System.Web.UI.WebControls.Panel pnlSonuc;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 306 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 312 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 319 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 307 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 311 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 317 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 310 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 314 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 315 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 309 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 318 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 305 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 313 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 308 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 323 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class contact_aspx : global::Default2, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public contact_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/contact.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.contact_aspx.@__initialized == false)) {
                global::ASP.contact_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/contact.aspx";
                dependencies[1] = "~/MasterPage.master";
                dependencies[2] = "~/MasterPage.master.cs";
                dependencies[3] = "~/contact.aspx.cs";
                global::ASP.contact_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.contact_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Literal @__BuildControlltlIletisim() {
            global::System.Web.UI.WebControls.Literal @__ctrl;
            
            #line 23 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Literal();
            
            #line default
            #line hidden
            this.ltlIletisim = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 23 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.ID = "ltlIletisim";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtAd() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtAd = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.ID = "txtAd";
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("required", "");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtMail() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 35 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtMail = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 35 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.ID = "txtMail";
            
            #line default
            #line hidden
            
            #line 35 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 35 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("required", "");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtTel() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 37 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtTel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 37 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.ID = "txtTel";
            
            #line default
            #line hidden
            
            #line 37 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 37 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("required", "");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtMesaj() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 39 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtMesaj = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 39 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.ID = "txtMesaj";
            
            #line default
            #line hidden
            
            #line 39 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.MultiLine;
            
            #line default
            #line hidden
            
            #line 39 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 39 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("required", "");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnGonder() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnGonder = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.ID = "btnGonder";
            
            #line default
            #line hidden
            
            #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.CssClass = "btn btn-default";
            
            #line default
            #line hidden
            
            #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.Text = "Submit";
            
            #line default
            #line hidden
            
            #line 42 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.Click += new System.EventHandler(this.Button1_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlIletisim() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlIletisim = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.ID = "pnlIletisim";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t\t  <h3 class=\"title\">Quick Contact</h3>\n\t\t\t  <div id=\"success\"></div>\n\t\t\t  <la" +
                        "bel>Name: <span class=\"required\">*</span></label>\n                  "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl1 = this.@__BuildControltxtAd();
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t\t  <label>Email Address: <span class=\"required\">*</span></label>\n             " +
                        "     "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl2;
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl2 = this.@__BuildControltxtMail();
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t\t  <label>Telephone:</label>\n                  "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl3 = this.@__BuildControltxtTel();
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t\t  <label>Comment:</label>\n                  "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl4 = this.@__BuildControltxtMesaj();
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t\t  <div class=\"clearfix\"></div>\n\t\t\t  <div class=\"buttons-box clearfix\">\n      " +
                        "            "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl5;
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl5 = this.@__BuildControlbtnGonder();
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t\t  </div><!-- .buttons-box -->\n                  "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlSonuc() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            
            #line 46 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            
            #line default
            #line hidden
            this.pnlSonuc = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 46 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.ID = "pnlSonuc";
            
            #line default
            #line hidden
            
            #line 46 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 46 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                  <h1 class=\"text-success\">SUCCESS!</h1>\r\n                   " +
                        "     <h2 class=\"text-success\">\r\n                            Your message has bee" +
                        "n sent. Thank you<br />\r\n                        </h2>\r\n              "));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(0, 378, true));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Literal @__ctrl1;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl1 = this.@__BuildControlltlIletisim();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t  </div>\n\n\n\t\t  <div class=\"col-sm-6 col-md-6 bottom-padding\">\n             \n  " +
                        "             "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl2;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl2 = this.@__BuildControlpnlIletisim();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\n              "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Panel @__ctrl3;
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl3 = this.@__BuildControlpnlSonuc();
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\t\t  </div>\n\n\n\t\t</div>\n      </div>\n    </div>\n  </div><!-- .container -->\n</sect" +
                        "ion><!-- #main -->\r\n\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(contact_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.MasterPageFile = "~/MasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__ctrl.EnableEventValidation = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 3 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 5 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\humanconsciousnessdecoded.com\httpdocs\contact.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.contact_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.contact_aspx.@__fileDependencies);
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 455503561;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
