-- HCD Next.js + Supabase schema
-- Run this in Supabase SQL Editor, then create:
--   1) a PUBLIC Storage bucket named `legacy-assets` (page images, media library),
--   2) a PRIVATE Storage bucket named `member-assets` (protected e-book downloads).

create extension if not exists pgcrypto;

create table if not exists public.content_types (
  id integer primary key,
  name text not null,
  title_label text,
  summary_label text,
  text_label text,
  has_picture boolean not null default false,
  has_categories boolean not null default false,
  has_tags boolean not null default false,
  has_sub_images boolean not null default false,
  has_sub_files boolean not null default false,
  is_protected boolean not null default false
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  type_id integer not null references public.content_types(id) on delete cascade,
  name text not null,
  rank integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  sub_page_id bigint references public.pages(id) on delete set null,
  category_id bigint references public.categories(id) on delete set null,
  type_id integer not null references public.content_types(id) on delete restrict,
  lang text not null default 'en',
  title text not null,
  summary text,
  body text,
  picture_url text,
  rank integer not null default 0,
  chck1 boolean not null default false,
  chck2 boolean not null default false,
  val1 text,
  val2 text,
  val3 text,
  val4 text,
  val5 text,
  val6 text,
  val7 text,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.files (
  id bigint generated by default as identity primary key,
  album_id bigint not null default 0,
  kind text not null check (kind in ('image', 'file')),
  extension text,
  title text,
  file_url text not null,
  rank integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  page_id bigint not null references public.pages(id) on delete cascade,
  tag text not null,
  unique (page_id, tag)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  telephone text,
  email text not null,
  subject text not null default 'ILETISIM / TALEP FORMU',
  message text not null,
  status text not null default 'new' check (status in ('new', 'read', 'archived')),
  created_at timestamptz not null default now()
);

create table if not exists public.mailing_list (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.site_options (
  name text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'admin',
  created_at timestamptz not null default now()
);

create table if not exists public.revision_requests (
  id bigint generated by default as identity primary key,
  title text not null,
  page_url text,
  description text not null,
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high')),
  status text not null default 'new' check (status in ('new', 'in_progress', 'done', 'rejected')),
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.revision_comments (
  id bigint generated by default as identity primary key,
  revision_id bigint not null references public.revision_requests(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists pages_type_lang_rank_idx on public.pages(type_id, lang, rank);
create index if not exists pages_published_idx on public.pages(published);
create index if not exists files_album_kind_rank_idx on public.files(album_id, kind, rank);
create index if not exists messages_status_idx on public.messages(status);
create index if not exists revision_requests_status_idx on public.revision_requests(status);
create index if not exists revision_requests_priority_idx on public.revision_requests(priority);
create index if not exists revision_comments_revision_idx on public.revision_comments(revision_id, created_at);

alter table public.content_types enable row level security;
alter table public.categories enable row level security;
alter table public.pages enable row level security;
alter table public.files enable row level security;
alter table public.tags enable row level security;
alter table public.messages enable row level security;
alter table public.mailing_list enable row level security;
alter table public.site_options enable row level security;
alter table public.admin_profiles enable row level security;
alter table public.revision_requests enable row level security;
alter table public.revision_comments enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_profiles
    where user_id = auth.uid()
  );
$$;

drop policy if exists "public read content types" on public.content_types;
create policy "public read content types" on public.content_types for select using (true);

drop policy if exists "public read categories" on public.categories;
create policy "public read categories" on public.categories for select using (true);

drop policy if exists "public read published pages" on public.pages;
create policy "public read published pages" on public.pages for select using (published = true);

drop policy if exists "public read files" on public.files;
create policy "public read files" on public.files for select using (true);

drop policy if exists "public read tags" on public.tags;
create policy "public read tags" on public.tags for select using (true);

drop policy if exists "public create messages" on public.messages;
create policy "public create messages" on public.messages for insert with check (true);

drop policy if exists "admin full content types" on public.content_types;
create policy "admin full content types" on public.content_types for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full categories" on public.categories;
create policy "admin full categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full pages" on public.pages;
create policy "admin full pages" on public.pages for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full files" on public.files;
create policy "admin full files" on public.files for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full tags" on public.tags;
create policy "admin full tags" on public.tags for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full messages" on public.messages;
create policy "admin full messages" on public.messages for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full mailing list" on public.mailing_list;
create policy "admin full mailing list" on public.mailing_list for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full site options" on public.site_options;
create policy "admin full site options" on public.site_options for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin read admin profiles" on public.admin_profiles;
create policy "admin read admin profiles" on public.admin_profiles for select using (public.is_admin());

drop policy if exists "admin full revision requests" on public.revision_requests;
create policy "admin full revision requests" on public.revision_requests for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full revision comments" on public.revision_comments;
create policy "admin full revision comments" on public.revision_comments for all using (public.is_admin()) with check (public.is_admin());

insert into public.content_types (
  id, name, title_label, summary_label, text_label, has_picture, has_categories, has_tags, has_sub_images, has_sub_files, is_protected
) values
  (1, 'Pages', 'Title', 'Summary', 'Content', true, false, false, true, false, false),
  (2, 'Blog', 'Title', 'Summary', 'Content', true, true, true, true, false, false),
  (3, 'Slider', 'Title', 'Description', null, true, false, false, false, false, false)
on conflict (id) do update set
  name = excluded.name,
  title_label = excluded.title_label,
  summary_label = excluded.summary_label,
  text_label = excluded.text_label,
  has_picture = excluded.has_picture,
  has_categories = excluded.has_categories,
  has_tags = excluded.has_tags,
  has_sub_images = excluded.has_sub_images,
  has_sub_files = excluded.has_sub_files,
  is_protected = excluded.is_protected;

insert into public.categories (id, type_id, name, rank) values
  (1, 2, 'Consciousness', 1),
  (2, 2, 'Human', 2),
  (3, 2, 'Book Notes', 3)
on conflict (id) do update set type_id = excluded.type_id, name = excluded.name, rank = excluded.rank;

insert into public.pages (
  id, category_id, type_id, lang, title, summary, body, picture_url, rank, val1, val2, val3, published
) values
  (1, null, 1, 'en', 'About HCD', 'Human Consciousness Decoded introduces a structured way to question human awareness, perception and behavior.', '<p>HCD is a long-form project by Burak Akcakanat about human consciousness, awareness and the inner mechanics of perception.</p>', 'books.jpg', 1, null, null, null, true),
  (6, null, 1, 'en', 'Contact', 'Contact Human Consciousness Decoded.', '<h3>Contact</h3><p>For questions, feedback and publishing inquiries, please use the quick contact form.</p><p><strong>Email:</strong> info@humanconsciousnessdecoded.com</p>', null, 2, null, null, null, true),
  (7, null, 1, 'en', 'Human Consciousness Decoded', 'A book and research project focused on decoding the invisible habits that shape human experience.', '<p class="lead">Human Consciousness Decoded is a practical and philosophical inquiry into consciousness, attention and identity.</p>', 'books2.jpg', 3, null, null, null, true),
  (10, 1, 2, 'en', 'What Is Consciousness?', 'A short introduction to the central question behind HCD.', '<p>Consciousness can be examined through repeated patterns of perception, reaction and meaning.</p>', 'book-small.png', 1, null, null, null, true),
  (11, 2, 2, 'en', 'The Human Pattern', 'How repetition becomes personality and behavior.', '<p>Human behavior is shaped by stored responses. Seeing those responses clearly is the first practical step toward change.</p>', 'world.jpg', 2, null, null, null, true),
  (12, 3, 2, 'en', 'Reading HCD', 'Available formats and where to buy the book.', '<p>The first edition of Human Consciousness Decoded is available as e-book and paperback through external bookstores.</p>', 'books.jpg', 3, null, null, null, true),
  (20, null, 3, 'en', 'Human Consciousness Decoded', null, null, 'slide.png', 1, 'Human Consciousness Decoded', 'A renewed home for Burak Akcakanat''s book and consciousness project.', '/i/1-about-hcd', true),
  (21, null, 3, 'en', 'Read the Book', null, null, 'books.jpg', 2, 'Read the Book', 'Choose e-book or paperback editions through trusted external stores.', '/books', true)
on conflict (id) do update set
  category_id = excluded.category_id,
  type_id = excluded.type_id,
  lang = excluded.lang,
  title = excluded.title,
  summary = excluded.summary,
  body = excluded.body,
  picture_url = excluded.picture_url,
  rank = excluded.rank,
  val1 = excluded.val1,
  val2 = excluded.val2,
  val3 = excluded.val3,
  published = excluded.published;

select setval(pg_get_serial_sequence('public.categories', 'id'), coalesce((select max(id) from public.categories), 1), true);
select setval(pg_get_serial_sequence('public.pages', 'id'), coalesce((select max(id) from public.pages), 1), true);

-- ============================================================
-- E-COMMERCE / MEMBERSHIP (legacy uye / siparis / hesaplar parity)
-- ============================================================

-- Members (legacy `uye`). Sifre(plaintext) -> password_hash (scrypt). Status 0/1 -> status text.
create table if not exists public.members (
  id            bigint generated by default as identity primary key,
  email         text not null unique,
  password_hash text not null,               -- format: scrypt$N$r$p$salt_b64$hash_b64
  full_name     text not null,               -- UyeAd
  country       text,                         -- UyeUlke
  status        text not null default 'pending' check (status in ('pending', 'active', 'blocked')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists members_email_idx on public.members (lower(email));

-- Products (legacy UrunId). Single seeded product, modeled as a table.
create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  title       text not null,
  price_cents integer not null default 999,
  currency    text not null default 'USD',
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

-- Orders (legacy `siparis`). Durum 0/1/2 -> pending/paid/completed (+cancelled).
create table if not exists public.orders (
  id                bigint generated by default as identity primary key,
  guid              uuid not null unique default gen_random_uuid(),
  product_id        bigint not null references public.products(id) on delete restrict,
  member_id         bigint not null references public.members(id) on delete cascade,
  buyer_name        text,
  amount_cents      integer not null,
  currency          text not null default 'USD',
  status            text not null default 'pending' check (status in ('pending', 'paid', 'completed', 'cancelled')),
  admin_note        text,
  paypal_order_id   text,
  paypal_capture_id text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists orders_member_idx on public.orders (member_id, created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_paypal_order_idx on public.orders (paypal_order_id);

-- Protected product assets (e-book files) stored in the PRIVATE `member-assets` bucket.
create table if not exists public.product_assets (
  id           bigint generated by default as identity primary key,
  product_id   bigint not null references public.products(id) on delete cascade,
  kind         text not null check (kind in ('mobi', 'epub', 'pdf', 'cover')),
  storage_path text not null,
  filename     text not null,
  created_at   timestamptz not null default now(),
  unique (product_id, kind)
);

-- Bank accounts (legacy `hesaplar`) for manual transfer instructions.
create table if not exists public.bank_accounts (
  id           bigint generated by default as identity primary key,
  bank_name    text not null,
  account_name text not null,
  branch_name  text,
  branch_code  text,
  account_no   text,
  iban         text,
  rank         integer not null default 0,
  created_at   timestamptz not null default now()
);

alter table public.members        enable row level security;
alter table public.products       enable row level security;
alter table public.orders         enable row level security;
alter table public.product_assets enable row level security;
alter table public.bank_accounts  enable row level security;

-- Public/anon read only for products + bank accounts. members/orders/product_assets have NO
-- anon policy -> the browser anon key sees nothing; all access flows through service-role/pg (server-only).
drop policy if exists "public read active products" on public.products;
create policy "public read active products" on public.products for select using (active = true);

drop policy if exists "public read bank accounts" on public.bank_accounts;
create policy "public read bank accounts" on public.bank_accounts for select using (true);

drop policy if exists "admin full members" on public.members;
create policy "admin full members" on public.members for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full products" on public.products;
create policy "admin full products" on public.products for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full orders" on public.orders;
create policy "admin full orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full product assets" on public.product_assets;
create policy "admin full product assets" on public.product_assets for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin full bank accounts" on public.bank_accounts;
create policy "admin full bank accounts" on public.bank_accounts for all using (public.is_admin()) with check (public.is_admin());

insert into public.products (slug, title, price_cents, currency, active)
values ('hcd-ebook', 'Human Consciousness Decoded (E-Book)', 999, 'USD', true)
on conflict (slug) do nothing;
